language: java
dist: bionic
addons:
  apt:
    update: true
    packages:
      - autoconf
      - aspcud
      - clang-8
      - curl
      - flex
      - gcc
      - libboost-all-dev
      - libffi-dev
      - libjemalloc-dev
      - libmpfr-dev
      - libtool
      - lld-8
      - llvm-8-tools
      - make
      - maven
      - ninja-build
      - ocaml
      - opam
      - openjdk-8-jdk
      - pandoc
      - pkg-config
      - python3
      - time
      - zlib1g-dev
      - z3
git:
    depth: 3
jobs:
    include:
#        - stage: ocaml
#          script: "./prover/ext/k/k-distribution/src/main/scripts/bin/k-configure-opam-dev"
        - stage: compile
          script: "cd prover && ./build prover-smt"
