language: java
dist: bionic
addons:
  apt:
    update: true
    packages:
      - autoconf
      - curl
      - flex
      - gcc
      - libffi-dev
      - libmpfr-dev
      - libtool
      - make
      - maven
      - ninja-build
      - opam
      - openjdk-8-jdk
      - pandoc
      - pkg-config
      - python3
      - time
      - zlib1g-dev
git:
    depth: 3
jobs:
    include:
        - state: compile
          script: "cd prover && ./build prover-smt"
        - script: "cd prover && ./build prover-kore"
