language: java
dist: bionic
addons:
  apt:
    update: true
    packages:
      - autoconf
      - clang-8
      - curl
      - flex
      - gcc
      - libboost-all-dev
      - libffi-dev
      - libjemalloc-dev
      - libmpfr-dev
      - libtool
      - lld-8
      - llvm-8-tools
      - make
      - maven
      - ninja-build
      - opam
      - openjdk-8-jdk
      - pandoc
      - pkg-config
      - python3
      - time
      - zlib1g-dev
      - z3
git:
    depth: 3
jobs:
    include:
        - stage: compile
          script: "cd prover && ./build unit-tests"
